SEND = True
CONFIRMATION_EMAIL = "navarre@mit.edu"
SEPARATOR = "@@@"
HEADER_ENDING = "###"
LAMBDA = "\\"
BOOLEAN_STRICT = True
BOOLEAN_DEFAULT = Exception
CSV_DELIMITER = "\t"
SERVER = "outgoing.mit.edu"
SLEEP_TIME = 1
DEFAULT_CONSTANTS = lambda: {}
